INSERT INTO [dbo].[WSP] ([WSP_Name], [WSP]) VALUES (N'WSP               ', CAST(1863.50 AS Decimal(18, 2)))
INSERT INTO [dbo].[WSP] ([WSP_Name], [WSP]) VALUES (N'LogGold           ', CAST(0.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[WSP] ([WSP_Name], [WSP]) VALUES (N'LogStat           ', CAST(0.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[WSP] ([WSP_Name], [WSP]) VALUES (N'sta/hp 251        ', CAST(0.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[WSP] ([WSP_Name], [WSP]) VALUES (N'Log_sta/hp 251    ', CAST(0.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[WSP] ([WSP_Name], [WSP]) VALUES (N'sta/wis 251       ', CAST(0.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[WSP] ([WSP_Name], [WSP]) VALUES (N'Log_sta/wis 251   ', CAST(0.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[WSP] ([WSP_Name], [WSP]) VALUES (N'sta/patt 251      ', CAST(0.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[WSP] ([WSP_Name], [WSP]) VALUES (N'Log_sta/patt 251  ', CAST(0.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[WSP] ([WSP_Name], [WSP]) VALUES (N'str/patt 251      ', CAST(0.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[WSP] ([WSP_Name], [WSP]) VALUES (N'Log_str/patt 251  ', CAST(0.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[WSP] ([WSP_Name], [WSP]) VALUES (N'dex/patt 251      ', CAST(0.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[WSP] ([WSP_Name], [WSP]) VALUES (N'Log_dex/patt 251  ', CAST(0.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[WSP] ([WSP_Name], [WSP]) VALUES (N'int/matt 251      ', CAST(0.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[WSP] ([WSP_Name], [WSP]) VALUES (N'Log_int/matt 251  ', CAST(0.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[WSP] ([WSP_Name], [WSP]) VALUES (N'int/matt          ', CAST(0.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[WSP] ([WSP_Name], [WSP]) VALUES (N'Log_int/matt      ', CAST(0.00 AS Decimal(18, 2)))
